//! Golden tests for `signer_core::tx` against vectors produced by `@solana/web3.js`.
//!
//! `fixtures/tx_vectors.json` is generated by `fixtures-gen/gen-tx-vectors.ts`, which
//! builds each transaction with the real web3.js encoder from fixed seeds and a fixed
//! blockhash and then records the exact bytes the TypeScript signer emits. ed25519
//! signing is deterministic, so `sign(unsigned) == ts_signed` is a byte-for-byte
//! compatibility oracle rather than a smoke test: if the Rust port places a signature
//! in a different slot, drops a pre-existing one, or re-encodes a shortvec length
//! differently, the comparison fails.
//!
//! The `v0_with_alt` vector's `expected.account_keys` and `expected.program_ids` are
//! recorded *after* address lookup table expansion, which needs the ALT module from a
//! later milestone. Its signing byte-equality test still runs — signing never consults
//! a lookup table — and its extraction is checked only for the parts that are
//! resolvable from the static keys.

use std::{str::FromStr, sync::OnceLock};

use base64::{engine::general_purpose::STANDARD as BASE64, Engine as _};
use serde::Deserialize;
use signer_core::tx::{ParsedTx, TxKind};
use solana_sdk::{
    pubkey::Pubkey,
    signature::Signature,
    signer::{
        keypair::{keypair_from_seed, Keypair},
        Signer as _,
    },
};

// ── Fixture ─────────────────────────────────────────────────────────────────

#[derive(Deserialize)]
struct Fixture {
    vectors: Vec<Vector>,
}

#[derive(Deserialize)]
struct Vector {
    name: String,
    kind: String,
    unsigned_b64: String,
    unsigned_len: usize,
    ts_signed_b64: String,
    ts_signed_len: usize,
    expected: Expected,
}

#[derive(Deserialize)]
struct Expected {
    fee_payer: String,
    recent_blockhash: String,
    num_instructions: usize,
    program_ids: Vec<String>,
    account_keys: Vec<String>,
    /// Versioned vectors only — the pre-expansion key list.
    #[serde(default)]
    static_account_keys: Vec<String>,
    address_table_lookups: Vec<Lookup>,
    signature_slots: Vec<SignatureSlot>,
}

#[derive(Deserialize)]
struct Lookup {
    account_key: String,
}

#[derive(Deserialize)]
struct SignatureSlot {
    index: usize,
    pubkey: String,
    present: bool,
}

impl Vector {
    fn tx_kind(&self) -> TxKind {
        self.kind
            .parse()
            .unwrap_or_else(|err| panic!("{}: bad kind in fixture: {err}", self.name))
    }

    fn unsigned(&self) -> Vec<u8> {
        decode(&self.unsigned_b64, &self.name)
    }

    fn ts_signed(&self) -> Vec<u8> {
        decode(&self.ts_signed_b64, &self.name)
    }

    /// Parses the unsigned bytes the bot would have put on the socket.
    fn parse_unsigned(&self) -> ParsedTx {
        ParsedTx::parse(self.tx_kind(), &self.unsigned())
            .unwrap_or_else(|err| panic!("{}: parse failed: {err}", self.name))
    }

    /// The signature slot the extraction tests may skip — see the module docs.
    fn needs_alt(&self) -> bool {
        !self.expected.address_table_lookups.is_empty()
    }
}

fn decode(b64: &str, name: &str) -> Vec<u8> {
    BASE64
        .decode(b64)
        .unwrap_or_else(|err| panic!("{name}: bad base64 in fixture: {err}"))
}

fn vectors() -> &'static [Vector] {
    static FIXTURE: OnceLock<Fixture> = OnceLock::new();
    &FIXTURE
        .get_or_init(|| {
            let raw = include_str!("fixtures/tx_vectors.json");
            serde_json::from_str(raw).expect("tx_vectors.json is not valid JSON for this schema")
        })
        .vectors
}

fn vector(name: &str) -> &'static Vector {
    vectors()
        .iter()
        .find(|v| v.name == name)
        .unwrap_or_else(|| panic!("fixture has no vector named {name}"))
}

// ── Key material (documented in tx_vectors.json `_fixed_material`) ──────────

fn keypair(seed_byte: u8) -> Keypair {
    keypair_from_seed(&[seed_byte; 32]).expect("32 bytes is a valid ed25519 seed")
}

/// The wallet the signer holds.
fn signer_keypair() -> Keypair {
    keypair(0x42)
}

/// The client-side co-signer of the `signLegacyWithExtra` flow.
fn extra_keypair() -> Keypair {
    keypair(0x43)
}

/// The transfer recipient. Never a required signer, but it *is* a static account
/// key of `v0_no_alt`, so it also covers "present in the key list, still not a
/// signing slot".
fn non_signer_keypair() -> Keypair {
    keypair(0x44)
}

fn pubkeys(keys: &[Pubkey]) -> Vec<String> {
    keys.iter().map(ToString::to_string).collect()
}

// ── 1. Parsing ──────────────────────────────────────────────────────────────

#[test]
fn parses_every_vector_into_the_declared_variant() {
    for v in vectors() {
        let bytes = v.unsigned();
        assert_eq!(
            bytes.len(),
            v.unsigned_len,
            "{}: fixture unsigned_len disagrees with the base64 payload",
            v.name
        );

        let parsed = v.parse_unsigned();
        assert_eq!(parsed.kind(), v.tx_kind(), "{}: wrong variant", v.name);
        assert!(
            match &parsed {
                ParsedTx::Legacy(_) => v.kind == "legacy",
                ParsedTx::Versioned(_) => v.kind == "versioned",
            },
            "{}: variant does not match the fixture kind",
            v.name
        );
    }
}

#[test]
fn parsing_preserves_the_message_header_and_signature_block() {
    for v in vectors() {
        let parsed = v.parse_unsigned();
        let e = &v.expected;

        let (fee_payer, blockhash, num_instructions, signatures) = match &parsed {
            ParsedTx::Legacy(tx) => (
                tx.message.account_keys[0],
                tx.message.recent_blockhash.to_string(),
                tx.message.instructions.len(),
                tx.signatures.clone(),
            ),
            ParsedTx::Versioned(tx) => (
                tx.message.static_account_keys()[0],
                tx.message.recent_blockhash().to_string(),
                tx.message.instructions().len(),
                tx.signatures.clone(),
            ),
        };

        assert_eq!(fee_payer.to_string(), e.fee_payer, "{}: fee payer", v.name);
        assert_eq!(blockhash, e.recent_blockhash, "{}: blockhash", v.name);
        assert_eq!(
            num_instructions, e.num_instructions,
            "{}: instruction count",
            v.name
        );

        // The unsigned bytes must carry exactly the slots the fixture recorded:
        // one per required signer, pre-filled only where a client-side co-signer
        // already signed.
        assert_eq!(
            signatures.len(),
            e.signature_slots.len(),
            "{}: signature slot count",
            v.name
        );
        for slot in &e.signature_slots {
            let filled = signatures[slot.index] != Signature::default();
            assert_eq!(
                filled, slot.present,
                "{}: signature slot {} ({}) presence",
                v.name, slot.index, slot.pubkey
            );
        }
    }
}

// ── 2. Byte-for-byte compatibility with the TypeScript signer ───────────────

#[test]
fn signing_reproduces_the_typescript_bytes_exactly() {
    let keypair = signer_keypair();

    for v in vectors() {
        let mut parsed = v.parse_unsigned();
        parsed
            .sign_with(&keypair)
            .unwrap_or_else(|err| panic!("{}: sign_with failed: {err}", v.name));

        let ours = parsed
            .to_bytes()
            .unwrap_or_else(|err| panic!("{}: to_bytes failed: {err}", v.name));
        let theirs = v.ts_signed();

        assert_eq!(
            theirs.len(),
            v.ts_signed_len,
            "{}: fixture ts_signed_len disagrees with the base64 payload",
            v.name
        );
        assert_eq!(
            ours.len(),
            theirs.len(),
            "{}: serialized length differs from web3.js",
            v.name
        );
        assert_eq!(
            ours,
            theirs,
            "{}: serialized bytes differ from web3.js\n  ours   {}\n  theirs {}",
            v.name,
            BASE64.encode(&ours),
            BASE64.encode(&theirs)
        );
    }
}

#[test]
fn signing_a_presigned_legacy_transaction_keeps_the_client_side_signature() {
    let v = vector("legacy_two_signer_presigned");
    let extra = extra_keypair().pubkey();

    let before = v.parse_unsigned();
    let ParsedTx::Legacy(before) = before else {
        panic!("fixture kind changed")
    };
    let extra_slot = v
        .expected
        .signature_slots
        .iter()
        .find(|slot| slot.pubkey == extra.to_string())
        .expect("fixture should record the pre-signed co-signer slot");
    assert!(
        extra_slot.present,
        "fixture should hand us the co-signer's signature already in place"
    );
    let presigned = before.signatures[extra_slot.index];

    let mut parsed = v.parse_unsigned();
    parsed.sign_with(&signer_keypair()).expect("sign");
    let ParsedTx::Legacy(after) = parsed else {
        panic!("kind changed while signing")
    };

    assert_eq!(
        after.signatures[extra_slot.index], presigned,
        "signing must not disturb a signature the client already placed"
    );
}

// ── 3. Extraction (pre-ALT) ────────────────────────────────────────────────

#[test]
fn extraction_matches_typescript_for_non_alt_vectors() {
    for v in vectors().iter().filter(|v| !v.needs_alt()) {
        let accounts = v.parse_unsigned().accounts();

        assert_eq!(
            pubkeys(&accounts.program_ids),
            v.expected.program_ids,
            "{}: program ids",
            v.name
        );
        assert_eq!(
            pubkeys(&accounts.account_keys),
            v.expected.account_keys,
            "{}: account keys",
            v.name
        );
        assert!(
            accounts.lookup_tables.is_empty(),
            "{}: no lookup tables expected",
            v.name
        );
        assert!(
            accounts.unresolved_program_ids.is_empty(),
            "{}: every program id should resolve from the static keys",
            v.name
        );

        if v.kind == "versioned" {
            assert_eq!(
                pubkeys(&accounts.account_keys),
                v.expected.static_account_keys,
                "{}: without lookup tables the static keys are the whole key list",
                v.name
            );
        }
    }
}

/// The ALT-dependent half of `v0_with_alt` belongs to a later milestone; what this
/// milestone owes is the pre-resolution state the ALT module will extend.
#[test]
fn extraction_defers_the_alt_vector_to_the_lookup_module() {
    let v = vector("v0_with_alt");
    let accounts = v.parse_unsigned().accounts();

    assert_eq!(
        pubkeys(&accounts.account_keys),
        v.expected.static_account_keys,
        "static keys are available without any lookup"
    );
    assert_eq!(
        pubkeys(&accounts.lookup_tables),
        v.expected
            .address_table_lookups
            .iter()
            .map(|l| l.account_key.clone())
            .collect::<Vec<_>>(),
        "the tables still to be fetched are reported in message order"
    );
    assert!(
        accounts.account_keys.len() < v.expected.account_keys.len(),
        "the fixture's key list is post-expansion, so it must be the longer one"
    );
}

// ── 4. Rejections ──────────────────────────────────────────────────────────

#[test]
fn signing_with_a_non_required_signer_is_rejected() {
    let intruder = non_signer_keypair();

    for name in ["legacy_spl_transfer", "v0_no_alt"] {
        let v = vector(name);
        let mut parsed = v.parse_unsigned();
        let err = parsed
            .sign_with(&intruder)
            .expect_err("a key that is not a required signer must not produce a signature");
        assert!(
            err.to_string().contains(&intruder.pubkey().to_string()),
            "{name}: the rejection should name the offending key, got: {err}"
        );
    }
}

#[test]
fn signing_a_legacy_transaction_missing_a_cosigner_is_rejected() {
    let v = vector("legacy_two_signer_presigned");
    let extra = extra_keypair().pubkey();
    let extra_slot = v
        .expected
        .signature_slots
        .iter()
        .find(|slot| slot.pubkey == extra.to_string())
        .expect("fixture should record the co-signer slot")
        .index;

    // Undo the client-side pre-signing: now only the signer key can be filled in,
    // and web3.js `serialize()` would refuse to emit the result.
    let mut parsed = v.parse_unsigned();
    let ParsedTx::Legacy(tx) = &mut parsed else {
        panic!("fixture kind changed")
    };
    tx.signatures[extra_slot] = Signature::default();

    let err = parsed
        .sign_with(&signer_keypair())
        .expect_err("a legacy transaction still missing a signature must not serialize");
    assert!(
        err.to_string().contains("Signature verification failed"),
        "unexpected error: {err}"
    );
}

#[test]
fn parsing_truncated_bytes_is_rejected() {
    for v in vectors() {
        let bytes = v.unsigned();
        for cut in [0, 1, bytes.len() / 2, bytes.len() - 1] {
            assert!(
                ParsedTx::parse(v.tx_kind(), &bytes[..cut]).is_err(),
                "{}: {cut} of {} bytes should not parse",
                v.name,
                bytes.len()
            );
        }
    }
}

#[test]
fn parsing_bytes_with_trailing_garbage_is_rejected() {
    // Accepting these would be worse than a parse failure: `to_bytes` re-encodes
    // from the parsed value, so the extra bytes would vanish from whatever the
    // caller believed it had signed.
    for v in vectors() {
        let mut bytes = v.unsigned();
        bytes.extend_from_slice(&[0u8; 8]);
        assert!(
            ParsedTx::parse(v.tx_kind(), &bytes).is_err(),
            "{}: trailing bytes should not parse",
            v.name
        );
    }
}

#[test]
fn parsing_garbage_is_rejected() {
    let garbage: [&[u8]; 4] = [&[], &[0xff; 32], &[0x00; 64], b"not a transaction at all"];
    for kind in [TxKind::Legacy, TxKind::Versioned] {
        for bytes in garbage {
            assert!(
                ParsedTx::parse(kind, bytes).is_err(),
                "{kind}: {} garbage bytes should not parse",
                bytes.len()
            );
        }
    }
}

#[test]
fn parsing_legacy_bytes_as_versioned_is_rejected() {
    // web3.js is lenient here — its version prefix is optional, so
    // `VersionedTransaction.deserialize` silently falls back to the legacy layout.
    // The port rejects a payload whose declared kind and real kind disagree.
    for name in ["legacy_spl_transfer", "legacy_two_signer_presigned"] {
        let bytes = vector(name).unsigned();
        let err = ParsedTx::parse(TxKind::Versioned, &bytes)
            .expect_err("legacy bytes must not be accepted as a versioned transaction");
        assert!(
            err.to_string().contains("legacy"),
            "{name}: the rejection should point at the right type, got: {err}"
        );
    }
}

#[test]
fn parsing_versioned_bytes_as_legacy_is_rejected() {
    for name in ["v0_no_alt", "v0_with_alt"] {
        let bytes = vector(name).unsigned();
        assert!(
            ParsedTx::parse(TxKind::Legacy, &bytes).is_err(),
            "{name}: v0 bytes must not be accepted as a legacy transaction"
        );
    }
}

// ── 5. Wire enum ───────────────────────────────────────────────────────────

#[test]
fn tx_kind_round_trips_the_wire_strings() {
    for kind in [TxKind::Legacy, TxKind::Versioned] {
        assert_eq!(
            TxKind::from_str(kind.as_str()).expect("as_str is a valid wire string"),
            kind
        );
    }
    assert_eq!(
        TxKind::from_str("legacy").expect("legacy is a wire string"),
        TxKind::Legacy
    );
    assert_eq!(
        TxKind::from_str("versioned").expect("versioned is a wire string"),
        TxKind::Versioned
    );

    for bad in ["Legacy", "VERSIONED", "v0", "", " legacy"] {
        let err = TxKind::from_str(bad).expect_err("only the exact wire strings are accepted");
        assert_eq!(err.to_string(), format!("Invalid type: {bad}"));
    }
}
