//! Transaction parse → sign → serialize, byte-compatible with `@solana/web3.js`.
//!
//! This is a port of `signTransaction` in `signer/index.ts`, which is three lines
//! of web3.js per branch:
//!
//! ```text
//! versioned: VersionedTransaction.deserialize(bytes) → tx.sign([keypair]) → tx.serialize()
//! legacy:    Transaction.from(bytes)                 → tx.partialSign(keypair) → tx.serialize()
//! ```
//!
//! The bytes on either side of that call are produced and re-parsed by web3.js in
//! the bot (`src/utils/wallet.ts`), so every observable detail has to match:
//! the shortvec length prefixes, the signature slot a signature lands in, which
//! pre-existing signatures survive, and which inputs are rejected outright.
//! `tests/tx_golden.rs` pins that down against vectors generated by the real
//! encoder.
//!
//! Two behaviours are worth calling out because they are asymmetric between the
//! branches, and both are deliberate — they mirror web3.js, not a tidier design:
//!
//! * **Legacy signing is checked, versioned signing is not.** `Transaction.serialize()`
//!   defaults to `verifySignatures: true`, so web3.js refuses to emit a legacy
//!   transaction that is not fully signed and valid. `VersionedTransaction.serialize()`
//!   has no such check and will happily emit a half-signed transaction.
//! * **Legacy signing is partial, versioned signing is positional.** `partialSign`
//!   leaves other slots alone, which is what makes the `signLegacyWithExtra` flow
//!   (extra keypair signs client-side, main key signs here) work at all.

use std::{fmt, str::FromStr};

use bincode::Options as _;
use solana_sdk::{
    message::VersionedMessage,
    pubkey::Pubkey,
    signer::{keypair::Keypair, Signer as _},
    transaction::{Transaction, VersionedTransaction},
};

use crate::error::{ProtocolError, TxError};

/// Which of the two transaction encodings a request carries.
///
/// The string forms are the `type` field of the socket request
/// (`{"type":"versioned"|"legacy","tx":"<base64>"}`) and are matched exactly —
/// `signer/index.ts` rejects anything else before it reaches the decoder.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum TxKind {
    /// A `VersionedTransaction` wrapping a v0 message (Jupiter swaps, the Byreal
    /// and PancakeSwap SDKs, auto-claim).
    Versioned,
    /// A legacy `Transaction` (Meteora, DAMM v2, the daily auto-convert).
    Legacy,
}

impl TxKind {
    /// The wire string for this kind, as it appears in the request `type` field.
    #[must_use]
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Versioned => "versioned",
            Self::Legacy => "legacy",
        }
    }
}

impl fmt::Display for TxKind {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

impl FromStr for TxKind {
    type Err = ProtocolError;

    /// # Errors
    ///
    /// Returns [`ProtocolError::InvalidType`] for anything other than the two
    /// exact wire strings, matching `Invalid type: ${request.type}` in
    /// `signer/index.ts`.
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "versioned" => Ok(Self::Versioned),
            "legacy" => Ok(Self::Legacy),
            other => Err(ProtocolError::InvalidType(other.to_owned())),
        }
    }
}

/// A transaction decoded from the wire, ready to be inspected and signed.
///
/// Construct one with [`ParsedTx::parse`] rather than the variants directly:
/// `parse` is the validating constructor, and the rest of this module leans on
/// its guarantees (signature count matches the header, account indexes are in
/// range for legacy messages) to stay panic-free.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ParsedTx {
    /// A legacy transaction.
    Legacy(Transaction),
    /// A versioned transaction. Always holds a v0 message — see [`ParsedTx::parse`].
    Versioned(VersionedTransaction),
}

impl ParsedTx {
    /// Decodes `bytes` as the given kind.
    ///
    /// Mirrors `VersionedTransaction.deserialize` / `Transaction.from` including
    /// their validation, with one deliberate divergence: web3.js lets
    /// `VersionedTransaction.deserialize` swallow a *legacy* message (the version
    /// prefix is optional, so the decoder falls back to the legacy layout), and
    /// this rejects it. The bot never produces that combination — `signVersioned`
    /// only ever serializes a `VersionedTransaction` built from a v0 message — and
    /// a signer should not quietly accept a payload whose declared shape and real
    /// shape disagree.
    ///
    /// # Errors
    ///
    /// [`TxError::DeserializeVersioned`] / [`TxError::DeserializeLegacy`] if the
    /// bytes are truncated, carry trailing garbage, declare a signature count that
    /// disagrees with the message header, reference an out-of-range account index,
    /// or (for [`TxKind::Versioned`]) turn out to hold a legacy message.
    pub fn parse(kind: TxKind, bytes: &[u8]) -> Result<Self, TxError> {
        match kind {
            TxKind::Legacy => {
                let tx: Transaction = bincode_options()
                    .deserialize(bytes)
                    .map_err(|err| TxError::DeserializeLegacy(err.to_string()))?;
                validate_legacy(&tx)?;
                Ok(Self::Legacy(tx))
            }
            TxKind::Versioned => {
                let tx: VersionedTransaction = bincode_options()
                    .deserialize(bytes)
                    .map_err(|err| TxError::DeserializeVersioned(err.to_string()))?;
                validate_versioned(&tx)?;
                Ok(Self::Versioned(tx))
            }
        }
    }

    /// Which encoding this transaction was parsed as.
    #[must_use]
    pub fn kind(&self) -> TxKind {
        match self {
            Self::Legacy(_) => TxKind::Legacy,
            Self::Versioned(_) => TxKind::Versioned,
        }
    }

    /// Adds `keypair`'s signature, leaving every other signature slot untouched.
    ///
    /// # Errors
    ///
    /// If `keypair` is not one of the transaction's required signers, or — for a
    /// legacy transaction — if the result is still missing a signature or one of
    /// the signatures present does not verify. See the module docs for why only
    /// the legacy branch checks.
    pub fn sign_with(&mut self, keypair: &Keypair) -> Result<(), TxError> {
        match self {
            Self::Legacy(tx) => sign_legacy(tx, keypair),
            Self::Versioned(tx) => sign_versioned(tx, keypair),
        }
    }

    /// Re-encodes the transaction for the wire.
    ///
    /// Byte-identical to `tx.serialize()` in web3.js, which is what makes this a
    /// drop-in replacement: the bot feeds the result straight back into
    /// `VersionedTransaction.deserialize` / `Transaction.from` and then to the RPC.
    ///
    /// # Errors
    ///
    /// [`TxError::DeserializeVersioned`] / [`TxError::DeserializeLegacy`] if
    /// encoding fails, which in practice means a transaction so large its shortvec
    /// lengths overflow.
    pub fn to_bytes(&self) -> Result<Vec<u8>, TxError> {
        match self {
            Self::Legacy(tx) => {
                bincode::serialize(tx).map_err(|err| TxError::DeserializeLegacy(err.to_string()))
            }
            Self::Versioned(tx) => {
                bincode::serialize(tx).map_err(|err| TxError::DeserializeVersioned(err.to_string()))
            }
        }
    }

    /// The account keys and program ids visible without resolving lookup tables.
    ///
    /// See [`TxAccounts`] for the ordering rules and the address-lookup-table
    /// boundary.
    #[must_use]
    pub fn accounts(&self) -> TxAccounts {
        match self {
            Self::Legacy(tx) => legacy_accounts(tx),
            Self::Versioned(tx) => versioned_accounts(tx),
        }
    }
}

/// What the policy engine can read off a transaction *before* any address lookup
/// table is fetched.
///
/// # Ordering
///
/// The two branches order their keys differently, and both orderings are load
/// bearing because the golden vectors were generated from the TypeScript that
/// makes the real allow/deny decision:
///
/// * **Legacy** (`signer/policy.ts`): `account_keys` is `[program_id, ...accounts]`
///   flattened over the instructions in order and deduplicated first-seen — *not*
///   the compiled `message.account_keys` order. `program_ids` has one entry per
///   instruction with duplicates kept, because `policy.ts` maps over instructions.
/// * **Versioned** (`signer/alt-resolver.ts`): `account_keys` is the static key
///   list in message order. `program_ids` is deduplicated first-seen, because
///   `extractProgramIds` collects into a `Set`.
///
/// # Address lookup table boundary
///
/// A v0 message can reference accounts that only exist in an on-chain lookup
/// table, which needs an RPC round trip and therefore lives in a later milestone.
/// This type describes the pre-resolution state and leaves room for that step:
///
/// * `account_keys` holds only the static keys. The ALT module appends the
///   writable lookups followed by the readonly lookups, which is the order
///   `resolveALTs` produces and the order every index in the message assumes.
/// * `lookup_tables` lists the tables to fetch, in message order.
/// * `unresolved_program_ids` names the instructions whose program id index points
///   past the static range, so the ALT module knows which entries of `program_ids`
///   are still missing rather than having to re-derive that.
///
/// For a legacy transaction and for a v0 message compiled without tables, the last
/// two fields are empty and the first is already complete.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TxAccounts {
    /// Account keys in the order described above.
    pub account_keys: Vec<Pubkey>,
    /// Program ids of the top-level instructions, in the order described above.
    pub program_ids: Vec<Pubkey>,
    /// Lookup tables the message references, in message order.
    pub lookup_tables: Vec<Pubkey>,
    /// Indexes of instructions whose program id could not be resolved from the
    /// static keys alone.
    pub unresolved_program_ids: Vec<usize>,
}

/// The bincode configuration Solana and web3.js agree on: fixed-width integers,
/// little endian, and nothing allowed past the end of the struct.
///
/// The trailing-bytes setting is the one that matters here. `bincode::deserialize`
/// permits trailing bytes, and a signer must not: [`ParsedTx::to_bytes`] re-encodes
/// from the parsed value, so anything the decoder skipped would silently disappear
/// from the transaction that actually gets broadcast.
fn bincode_options() -> impl bincode::Options {
    bincode::DefaultOptions::new()
        .with_fixint_encoding()
        .reject_trailing_bytes()
}

/// Rejects a versioned transaction that would panic or misbehave downstream.
///
/// The signature-count check is the assertion in the `VersionedTransaction`
/// constructor, which `deserialize` runs on every payload.
fn validate_versioned(tx: &VersionedTransaction) -> Result<(), TxError> {
    if matches!(tx.message, VersionedMessage::Legacy(_)) {
        return Err(TxError::DeserializeVersioned(
            "message has no version prefix — send a legacy transaction with type \"legacy\""
                .to_owned(),
        ));
    }

    let required = usize::from(tx.message.header().num_required_signatures);
    if tx.signatures.len() != required {
        return Err(TxError::DeserializeVersioned(format!(
            "expected signatures length to be equal to the number of required signatures \
             ({required}), got {}",
            tx.signatures.len()
        )));
    }

    let static_keys = tx.message.static_account_keys().len();
    if static_keys < required {
        return Err(TxError::DeserializeVersioned(format!(
            "{required} required signatures but only {static_keys} static account keys"
        )));
    }

    Ok(())
}

/// Rejects a legacy transaction that would panic or misbehave downstream.
///
/// A legacy message has no lookup tables, so every account index has to resolve
/// against `account_keys`. web3.js reaches the same conclusion by a slower route —
/// an out-of-range index yields `undefined`, and the first `.toBase58()` on it
/// throws — but checking up front keeps the signing and extraction paths total.
fn validate_legacy(tx: &Transaction) -> Result<(), TxError> {
    let required = usize::from(tx.message.header.num_required_signatures);
    if tx.signatures.len() != required {
        return Err(TxError::DeserializeLegacy(format!(
            "{required} required signatures but the signature block holds {}",
            tx.signatures.len()
        )));
    }

    let num_keys = tx.message.account_keys.len();
    if num_keys < required {
        return Err(TxError::DeserializeLegacy(format!(
            "{required} required signatures but only {num_keys} account keys"
        )));
    }

    for (ix_index, ix) in tx.message.instructions.iter().enumerate() {
        let out_of_range = std::iter::once(ix.program_id_index)
            .chain(ix.accounts.iter().copied())
            .find(|index| usize::from(*index) >= num_keys);
        if let Some(index) = out_of_range {
            return Err(TxError::DeserializeLegacy(format!(
                "instruction {ix_index} references account index {index} but there are only \
                 {num_keys} account keys"
            )));
        }
    }

    Ok(())
}

/// Signs in place the way `VersionedTransaction.sign([keypair])` does: one
/// signature over `message.serialize()`, dropped into the slot matching the
/// keypair's position among the required signers.
fn sign_versioned(tx: &mut VersionedTransaction, keypair: &Keypair) -> Result<(), TxError> {
    let pubkey = keypair.pubkey();
    let required = usize::from(tx.message.header().num_required_signatures);

    // Only the first `num_required_signatures` static keys are signers, and the
    // signature index *is* the key index — a match further down the list is a
    // read-only account that happens to be this wallet, not a signing slot.
    let slot = tx
        .message
        .static_account_keys()
        .iter()
        .take(required)
        .position(|key| *key == pubkey)
        .ok_or_else(|| {
            TxError::DeserializeVersioned(format!("Cannot sign with non signer key {pubkey}"))
        })?;

    let signature = keypair.sign_message(&tx.message.serialize());
    *tx.signatures.get_mut(slot).ok_or_else(|| {
        TxError::DeserializeVersioned("signature block is too short".to_owned())
    })? = signature;

    Ok(())
}

/// Signs in place the way `partialSign(keypair)` followed by `serialize()` does.
///
/// Passing the message's own blockhash back to `try_partial_sign` is what keeps
/// signatures already in the block: handing it a *different* blockhash is the
/// documented way to tell the SDK the message changed, and it responds by clearing
/// every slot. The `signLegacyWithExtra` flow depends on that not happening.
fn sign_legacy(tx: &mut Transaction, keypair: &Keypair) -> Result<(), TxError> {
    let blockhash = tx.message.recent_blockhash;
    tx.try_partial_sign(&[keypair], blockhash).map_err(|err| {
        TxError::DeserializeLegacy(format!(
            "Cannot sign with non signer key {}: {err}",
            keypair.pubkey()
        ))
    })?;

    // `serialize()` in web3.js defaults to requireAllSignatures + verifySignatures,
    // so a transaction still missing a co-signer never makes it onto the wire.
    if !tx.is_signed() {
        return Err(TxError::DeserializeLegacy(
            "Signature verification failed: transaction is not fully signed".to_owned(),
        ));
    }
    tx.verify()
        .map_err(|err| TxError::DeserializeLegacy(format!("Signature verification failed: {err}")))
}

/// Extraction for the legacy branch of `signer/policy.ts` — see [`TxAccounts`].
fn legacy_accounts(tx: &Transaction) -> TxAccounts {
    let keys = &tx.message.account_keys;
    let mut account_keys = Vec::new();
    let mut program_ids = Vec::with_capacity(tx.message.instructions.len());

    for ix in &tx.message.instructions {
        // `validate_legacy` has already bounds-checked every index; the `else`
        // arms only matter for a `ParsedTx::Legacy` built without `parse`.
        let Some(program_id) = keys.get(usize::from(ix.program_id_index)).copied() else {
            continue;
        };
        program_ids.push(program_id);
        push_unique(&mut account_keys, program_id);
        for index in &ix.accounts {
            if let Some(key) = keys.get(usize::from(*index)).copied() {
                push_unique(&mut account_keys, key);
            }
        }
    }

    TxAccounts {
        account_keys,
        program_ids,
        lookup_tables: Vec::new(),
        unresolved_program_ids: Vec::new(),
    }
}

/// Extraction for the versioned branch (`extractProgramIds`) — see [`TxAccounts`].
fn versioned_accounts(tx: &VersionedTransaction) -> TxAccounts {
    let static_keys = tx.message.static_account_keys();
    let mut program_ids = Vec::new();
    let mut unresolved_program_ids = Vec::new();

    for (ix_index, ix) in tx.message.instructions().iter().enumerate() {
        if let Some(program_id) = static_keys.get(usize::from(ix.program_id_index)) {
            push_unique(&mut program_ids, *program_id);
        } else {
            unresolved_program_ids.push(ix_index);
        }
    }

    let lookup_tables = tx
        .message
        .address_table_lookups()
        .map(|lookups| lookups.iter().map(|lookup| lookup.account_key).collect())
        .unwrap_or_default();

    TxAccounts {
        account_keys: static_keys.to_vec(),
        program_ids,
        lookup_tables,
        unresolved_program_ids,
    }
}

/// Appends `key` unless it is already present, preserving first-seen order.
///
/// Linear scan on purpose: these lists are bounded by the transaction account
/// limit, and the allocation a hash set would cost is not worth saving.
fn push_unique(keys: &mut Vec<Pubkey>, key: Pubkey) {
    if !keys.contains(&key) {
        keys.push(key);
    }
}
